--punto 2 
--a
create tablespace  UBER
datafile 'UBER_1.DBF' size 2G;
--b
CREATE UNDO TABLESPACE undots1
DATAFILE 'undotbs_1a.dbf' SIZE 25M;
--c
create BIGFILE TABLESPACE bigtbs 
datafile 'bigtbs01' size 5G;
--d
ALTER SYSTEM SET UNDO_TABLESPACE = undots1;

-- punto 3
CREATE USER user1 IDENTIFIED BY AdminUser
DEFAULT TABLESPACE UBER 
QUOTA UNLIMITED ON UBER;
GRANT DBA TO user1;
GRANT CONNECT TO user1;

--punto 4
--a
  CREATE PROFILE clerk LIMIT 
  SESSIONS_PER_USER                 1  
  IDLE_TIME                        10   
  FAILED_LOGIN_ATTEMPTS             4   
  PASSWORD_LIFE_TIME               40;  
--b
  CREATE PROFILE development LIMIT 
  SESSIONS_PER_USER                 2   
  IDLE_TIME                         30
  PASSWORD_LIFE_TIME               100;
  
--punto 5
--a
CREATE USER UserA
IDENTIFIED BY userA
DEFAULT TABLESPACE UBER
QUOTA UNLIMITED ON UBER
PROFILE clerk; 

CREATE USER UserB
IDENTIFIED BY userB
DEFAULT TABLESPACE UBER
QUOTA UNLIMITED ON UBER
PROFILE clerk;

CREATE USER UserC
IDENTIFIED BY userC
DEFAULT TABLESPACE UBER
QUOTA UNLIMITED ON UBER
PROFILE development;

CREATE USER UserD
IDENTIFIED BY userD
DEFAULT TABLESPACE UBER
QUOTA UNLIMITED ON UBER
PROFILE development;

GRANT CONNECT TO UserA;
GRANT CONNECT TO UserB;
GRANT CONNECT TO UserC;
GRANT CONNECT TO UserD;
--b
ALTER USER UserA ACCOUNT LOCK;


